/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Conexion;
import Clases.DropExcel;
import java.awt.BorderLayout;
//import Frames.MenuPrincipal;
//import Frames.Menuimpo;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alberto Alvarez
 */
public class update extends javax.swing.JFrame {

    Conexion con = new Conexion();
    // DefaultTableModel modelo = new DefaultTableModel();
    String Ubicacion;
    /**
     * Creates new form Actualizacion
     */

    DropExcel de;

    public update() {
        initComponents();
        TableImpo.setRowHeight(40);
        setTitle("Batesville-Chihuahua Actualizacion"); // Titulo
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icon.png")).getImage());
        ((JPanel) getContentPane()).setOpaque(false); //imagen fondo
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/Imagenes/test26.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
        de = new DropExcel(TableImpo);
        buttonIcon();

//        TableImpo.getTableHeader().setFont(new Font("Times New Roman", 1, 16));
//        TableImpo.getTableHeader().setBackground(Color.DARK_GRAY);
//        TableImpo.getTableHeader().setFont(new Font("Times New Roman", 1, 16));
//        TableImpo.getTableHeader().setBackground(Color.DARK_GRAY);
    }
    String directory = System.getProperty("user.dir");
    private void buttonIcon() {
        String imageRoute;
        imageRoute = directory + "\\Imagenes\\" + "ayuda.png";
        ImageIcon imagen = new ImageIcon(imageRoute);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(labelHelp.getWidth(), labelHelp.getHeight(), Image.SCALE_DEFAULT));
        labelHelp.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnImportar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableImpo = new javax.swing.JTable();
        labelHelp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 48)); // NOI18N
        jLabel2.setText("Actualizar Base de Datos");

        btnImportar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnImportar.setText("Importar");
        btnImportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImportarMouseClicked(evt);
            }
        });
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        TableImpo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TableImpo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableImpo);

        labelHelp.setToolTipText("Ayuda!!!");
        labelHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHelpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*    */
    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Principal P = new Principal();
        P.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnImportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportarMouseClicked
        //Ciclo para insertar los datos de la tabla en la base de datos
        for (int i = 0; i < TableImpo.getRowCount(); i++) {

            String sql = "insert into usuarios values ("
                    + TableImpo.getValueAt(i, 0) + ",'"
                    + TableImpo.getValueAt(i, 1) + "','"
                    + TableImpo.getValueAt(i, 2) + "','"
                    + TableImpo.getValueAt(i, 3) + "','"
                    + TableImpo.getValueAt(i, 4) + "','"
                    + TableImpo.getValueAt(i, 5) + "','"
                    + TableImpo.getValueAt(i, 6) + "','"
                    + TableImpo.getValueAt(i, 7) + "')";
            
            try {
                con.ConectarBasedeDatos();
                con.sentencia.execute(sql);
                con.DesconectarBasedeDatos();
                System.out.println("Datos agregados correctamente");
            } catch (Exception e) {
                System.out.println("Ocurrio un error al insertar los datos");
            }
        }
    }//GEN-LAST:event_btnImportarMouseClicked

    private void labelHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHelpMouseClicked
        JOptionPane.showMessageDialog(null, "Para actualizar la base de datos, arrastrar\nel archivo y soltar en la parte superior blanca de la tabla,\nel archivo tiene que ser formato 97-2003");
    }//GEN-LAST:event_labelHelpMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableImpo;
    public javax.swing.JButton btnImportar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHelp;
    // End of variables declaration//GEN-END:variables

    /*
    private String obtenercontenido(int fila, int columna) {
        Object palabraOB = TableImpo.getValueAt(fila, columna);
        String palabra = "";
        if (palabraOB != null) {
            palabra = palabraOB.toString();
        }
        return palabra;
    }*/
}
